version: '3'
services:
  signup-login:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443

  cassandra-container:
    image: cassandra:latest
    networks:
      default:
        ipv4_address: 172.17.0.3
